export const menuArray = [
  {
    name: "Pizza",
    ingredients: ["pepperoni", "mushrom", "mozarella"],
    id: 0,
    quantity: 0,
    price: 14,
    isRendered: false,
    emoji: "🍕",
  },
  {
    name: "Hamburger",
    ingredients: ["beef", "cheese", "lettuce"],
    price: 12,
    quantity: 0,
    isRendered: false,
    emoji: "🍔",
    id: 1,
  },
  {
    name: "Beer",
    ingredients: ["grain, hops, yeast, water"],
    price: 12,
    quantity: 0,
    isRendered: false,
    emoji: "🍺",
    id: 2,
  },
  {
    name: "Sandwich",
    ingredients: ["cheese, bread, butter, "],
    price: 10,
    quantity: 0,
    isRendered: false,
    emoji: "🥪",
    id: 3,
  },
];
